config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'projects#index'

  resources :projects
  resources :machines

  resources :builds, only: [:show, :create, :update, :destroy]

end

app/models/audit_log.rb
class AuditLog < ActiveRecord::Base
  belongs_to :users
  belongs_to :projects
  belongs_to :builds
end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :project
  belongs_to :machines
  has_many :audit_logs

  STATE = {
    wait: "wait",
    building: "building",
    end: "end"
  }

  def pretty_commit n=7
    self.commit[0..n]
  end

  def commit_url
    self.project.uri + "/commit/#{self.commit}"
  end
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_many :builds
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :builds
  has_many :audit_logs

  validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :audit_logs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :authenticate_user!, :except => :create
  protect_from_forgery :except => :create
  
  def show
    load_build
    load_project
  end

  def create
    load_project
    build_build
    save_build
    perform_build
    redirect_to @project
  end

  def update
    load_build
    perform_build
    redirect_to @build
  end

  def destroy
    load_build
    load_project
    @build.destroy
    redirect_to @project
  end

  private

  def load_build
    @build ||= Build.find(params[:id])
  end

  def load_project
    @project ||= @build.project unless @build.blank?
    @project ||= Project.find(params[:project_id])
  end

  def build_build
    @build ||= Build.new
    @build.project_id = @project.id
    @build.commit = "test"
    @build.state = Build::STATE[:wait]
  end

  def save_build
    @build.save
  end

  def perform_build
    ProjectBuildJob.perform_later @build
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :authenticate_user!

  def index
    load_machines
  end

  def new
    build_machine
  end

  def create
    build_machine
    save_machine or render :new
  end

  def destroy
    load_machine
    @machine.destroy
    redirect_to machines_path
  end

  private

  def load_machines
    @machines ||= Machine.all
  end

  def load_machine
    @machine ||= Machine.find(params[:id])
  end

  def build_machine
    @machine ||= Machine.new
    @machine.attributes = machine_params
  end

  def save_machine
    if @machine.save
      redirect_to machines_path
    end
  end

  def machine_params
    machine_params = params[:machine]
    machine_params ? machine_params.permit(:name, :url, :login_user) : {}
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    load_projects
  end

  def show
    load_project
    load_builds
  end

  def new
    build_project
  end

  def create
    build_project
    save_project or render :new
  end

  def edit
   load_project
   build_project
  end

  def update
    load_project
    build_project
    save_project or render :edit
  end

  def destroy
    load_project
    @project.destroy
    redirect_to projects_path
  end

  private

  def load_projects
    @projects ||= Project.all
  end

  def load_project
    @project ||= Project.find(params[:id])
  end

  def load_builds
    @builds = @project.builds.order(updated_at: :desc)
  end

  def build_project
    @project ||= Project.new
    @project.attributes = project_params
  end

  def save_project
    if @project.save
      redirect_to @project
    end
  end

  def project_params
    project_params = params[:project]
    project_params ? project_params.permit(:name, :uri, :docker_uri, :branch, :script) : {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
  def state_color build, text=false
    ret = case build.state
          when Build::STATE[:wait]
            "grey lighten-1"
          when Build::STATE[:building]
            "amber lighten-2"
          when Build::STATE[:end]
            build.exit_status == 0 ? "lime lighten-1" : "deep-orange lighten-1"
          else
            "white"
          end
    text ? ret.gsub(/ /, "-text text-") : ret
  end

  def pretty_output output
    h(output).gsub(/[\n\r]/, '<br />')
  end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/builds/show.html.erb
<div class="container">
  <div class="card-panel">
    <div class="row">
      <div class="col s12">
        <h3>
          <span><%= link_to @project.name, project_path(@project), class: "" %></span>/<span><%= link_to @build.pretty_commit, @build.commit_url, class: state_color(@build, true), target: "_blank" %></span>
        </h3>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <%= link_to "Rebuild", build_path(@build), method: :put, class: "waves-effect waves-light btn lime darken-3" %>
        <%= link_to "Delete", build_path(@build), method: :delete, class: "waves-effect waves-light btn red" %>
      </div>
    </div>
  </div>
</div>

<div class="container">

  <div class="card-panel black">

      <div class="row">
        <div class="col s12">
          <p class="flow-text white-text">
            <%= pretty_output(@build.stdout).html_safe %>
          </p>
        </div>
      </div>
  </div>
</div>

app/views/common/_header.html.erb
<!-- Dropdown Structure -->
<ul id="account-dropdown" class="dropdown-content">
  <% if current_user.present? %>
    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

<nav class="top-nav">
  <div class="container">
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">DuckCI</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "Create Project", new_project_path %></li>
        <li><%= link_to "Add Node", new_machine_path %></li>

        <li>
          <% if current_user.present? %>
            <a class="dropdown-button" href="#!" data-activates="account-dropdown"><%= current_user.email %><i class="mdi-navigation-arrow-drop-down right"></i></a>
          <% else %>
            <a class="dropdown-button" href="#!" data-activates="account-dropdown"><i class="mdi-social-person"></i></a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DuckCI</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'common/header' %>

<%= yield %>

</body>
</html>

app/views/machines/_form.html.erb
<%= form_for @machine do |f| %>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :name, value: @machine.name, id: "name", class: "validate #{@machine.errors.blank? ? '' : 'invalid'}" %>
      <label for="name">Name</label>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :url, value: @machine.url, id: "url", class: "validate" %> 
      <label for="url">Node URI</label>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :login_user, value: @machine.login_user, id: "login_user", class: "validate" %> 
      <label for="login_user">Login User</label>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <button class="btn waves-effect waves-light" type="submit" name="action">Submit
        <i class="mdi-content-send right"></i>
      </button>
    </div>
  </div>

<% end %>

app/views/machines/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <ul class="collection with-header">
        <li class="collection-header"><h4>Nodes</h4></li>
        <% @machines.each do |m| %>
          <%= link_to m.name, '#', class: "collection-item" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/machines/new.html.erb
<div class="container">
  <div class="card-panel">
    <div class="row">
      <div class="col s12">
        <h4>New Node</h4>
      </div>
    </div>

    <%= render 'machines/form' %>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :name, value: @project.name, id: "name", class: "validate #{@project.errors.blank? ? '' : 'invalid'}" %>
      <label for="name">Name</label>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :uri, value: @project.uri, id: "uri", class: "validate" %> 
      <label for="uri">Repository URI</label>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :docker_uri, value: @project.docker_uri, id: "docker_uri", class: "validate" %> 
      <label for="docker_uri">Docker URI</label>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :branch, value: @project.branch, id: "branch", class: "validate" %> 
      <label for="branch">Branch to track</label>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_area :script, value: @project.script, id: "script", class: "materialize-textarea" %> 
      <label for="script">Build script</label>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <button class="btn waves-effect waves-light" type="submit" name="action">Submit
        <i class="mdi-content-send right"></i>
      </button>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <div class="card-panel">
    <div class="row">
      <div class="col s12">
        <h4>Edit Project</h4>
      </div>
    </div>

    <%= render 'projects/form' %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <ul class="collection with-header">
        <li class="collection-header"><h4>Projects</h4></li>
        <% @projects.each do |p| %>
          <%= link_to p.name, project_path(p), class: "collection-item" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="card-panel">
    <div class="row">
      <div class="col s12">
        <h4>New Project</h4>
      </div>
    </div>

    <%= render 'projects/form' %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="card-panel">
    <div class="row">
      <div class="col s12">
        <h3><%= @project.name %></h3>
        <%= link_to @project.uri, @project.uri, class: "teal-text text-lighten-2", target: "_blank" %>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <%= link_to "Build", builds_path(project_id: @project.id), method: :post, class: "waves-effect waves-light btn lime darken-3" %>
        <%= link_to "Edit", edit_project_path(@project), class: "waves-effect waves-light btn" %>
        <%= link_to "Delete", project_path(@project), method: :delete, class: "waves-effect waves-light btn red" %>
      </div>
    </div>

  </div>
</div>


<div class="container">
  <h3>Builds</h3>

  <div class="row">
    <div class="col s12">
      <ul class="collapsible popout" data-collapsible="accordion">
        <% @builds.each do |b| %>
          <li>
            <div class="collapsible-header <%= state_color b %>">
              <%= link_to build_path(b), class: "black-text" do %>
                <%= b.pretty_commit %>
                by <%= b.author %>
              <% end %>
              <div class="right">
                <%= link_to "Rebuild", build_path(b), method: :put, class: "waves-effect waves-light btn light-green darken-2" %>
                <%= link_to "Delete", build_path(b), method: :delete, class: "waves-effect waves-light btn red" %>
              </div>
            </div>
            <div class="collapsible-body">
              <p class="flow-text black white-text">
                <%= pretty_output(b.stdout).html_safe %>
              </p>
            </div>
          </li>
        <% end %>
      </ul>

    </div>
  </div>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>